### PR TITLE
Add a writeup for the puzzle

### PR DESCRIPTION
**Pull request by depili**
Since the tickets are gone and the original repository is little confusing here is some additional help.

### CODE REVIEW

**Comment by rebane2001** [comment]
LGTM 👍

**Comment by depili** [comment]
Another writeup: https://gofore.com/en/disobey-2025-hacker-puzzle-walkthrough/

**Comment by depili** [comment]
And another: https://github.com/JubinBlack/Disobey25

**Comment by BlueOcean110** [comment]
No commits to this repo please. You can add links to README.md.

**Pull request closed without merging**
